global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnetcore'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']  # Update this to match your application's URL and port
